name: 'Build TrayIt!'

on:
  workflow_dispatch:
  
defaults:
  run:
    working-directory: src
    
jobs:
  build:
    runs-on: windows-2019
    strategy:
      matrix:
        arch:
          - amd64
          - amd64_x86
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set Up Environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
      - name: Build TrayIt!
        run: |
          set INCLUDE=%INCLUDE%;%GITHUB_WORKSPACE%\src\include
          set INCLUDEDIR=%GITHUB_WORKSPACE%\src\include
          nmake
