name: 'Build TrayIt!'

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: src

jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: Install compiler
      id: install_cc
      uses: rlalik/setup-cpp-compiler@master
      with:
        compiler: gcc-6.40
    - name: Use compiler
      shell: bash
      env:
            CC: ${{ steps.install_cc.outputs.cc }}
      run: |
        mkdir ../build
        cd ../build
    - name: build application
      run: make build ./src
