name: 'Build TrayIt!'

on:
  workflow_dispatch:
  
defaults:
  run:
    working-directory: src
    
jobs:
  build:
    runs-on: windows-2019
    strategy:
      matrix:
        arch:
          - amd64
          - amd64_x86
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
      - name: Build something requiring CL.EXE
        run: |
          nmake
